# Generated by Django 4.1.9 on 2023-07-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=1008),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrate',
            field=models.FloatField(default=24.2),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.FloatField(default=14.4),
        ),
        migrations.AddField(
            model_name='product',
            name='jirnost',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='product',
            name='massa',
            field=models.IntegerField(default=105),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=3.7),
        ),
        migrations.AddField(
            model_name='product',
            name='srok_godnosti',
            field=models.IntegerField(default=18, help_text='Указывается в месяцах'),
        ),
        migrations.AddField(
            model_name='product',
            name='temperature',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='product',
            name='upakovka',
            field=models.CharField(default='Флоу-Пак', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category'),
            preserve_default=False,
        ),
    ]
