# Generated by Django 4.1.9 on 2023-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='logos')),
                ('photo_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.CharField(max_length=20)),
                ('kaspi', models.CharField(max_length=12)),
            ],
        ),
    ]
