# Generated by Django 4.1.9 on 2023-08-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
