# Generated by Django 4.1.9 on 2023-07-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_calories_product_carbohydrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
