# Generated by Django 4.1.9 on 2023-08-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_organization_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
