# Generated by Django 4.1.9 on 2023-07-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userlocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
