# Generated by Django 4.1.9 on 2023-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_photo_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
