# Generated by Django 4.1.9 on 2023-07-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_updated',
            field=models.BooleanField(default=False),
        ),
    ]
