# Generated by Django 4.1.9 on 2023-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_organization_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kaspi_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
