# Generated by Django 4.1.9 on 2023-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_organization_kaspi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
