# Generated by Django 4.1.9 on 2023-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_subscriptionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
