# Generated by Django 4.1.9 on 2023-07-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderproduct_delete_customuser_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=30),
        ),
    ]
