# Generated by Django 4.1.9 on 2023-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
