# Generated by Django 4.1.9 on 2023-08-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
