# Generated by Django 4.1.9 on 2023-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_subscriber_order_alter_subscriber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='org',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
